version: '3.8'

services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
    environment:
      - NODE_ENV=development

  backend:
    build:
      dockerfile: server/Dockerfile
    ports:
      - "3007:3007"
    environment:
      - NODE_ENV=development
    env_file:
      - .env